# Change these first
owner: AylaAI # Your GitHub organization or username, where this repository lives
repo: status-monitor-upptime # The name of this repository

env:
  NOTIFICATION_DISCORD: "true"
  NOTIFICATION_DISCORD_WEBHOOK: "true"
  NOTIFICATION_DISCORD_WEBHOOK_URL: ${{ secrets.NOTIFICATION_DISCORD_WEBHOOK_URL }}
  AYLA_STATUS_ENDPOINT: ${{ secrets.AYLA_STATUS_ENDPOINT }}

sites:
  - name: test email notifications
    url: https://d.ayla-app.org
  - name: Platform Status Endpoint
    url: $AYLA_STATUS_ENDPOINT
    method: GET
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: '"status": "OK"'

  - name: Redis Service
    url: $AYLA_STATUS_ENDPOINT
    method: GET
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: "Redis is running"

  - name: Milvus Service
    url: $AYLA_STATUS_ENDPOINT
    method: GET
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: "Milvus is running"

  - name: MongoDB Service
    url: $AYLA_STATUS_ENDPOINT
    method: GET
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: "MongoDB is running"

  - name: API Server
    url: $AYLA_STATUS_ENDPOINT
    method: GET
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: "api_server is running"

  - name: Audio Server
    url: $AYLA_STATUS_ENDPOINT
    method: GET
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: "audio_server is running"

  - name: Chatbot Server
    url: $AYLA_STATUS_ENDPOINT
    method: GET
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: "chatbot_server is running"

  - name: TTS Server
    url: $AYLA_STATUS_ENDPOINT
    method: GET
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: "tts_server is running"

  - name: Conversation Cron Task
    url: $AYLA_STATUS_ENDPOINT
    method: GET
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: "conversation_cron_task is running"

  - name: VisitAssist Phone Recording Pull Cron
    url: $AYLA_STATUS_ENDPOINT
    method: GET
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: "dr_visit_phone_recording_pull_cron_task is running"

  - name: VisitAssist Summary Cron
    url: $AYLA_STATUS_ENDPOINT
    method: GET
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: "dr_visit_summary_cron_task is running"

  - name: CareNote Cron
    url: $AYLA_STATUS_ENDPOINT
    method: GET
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: "carenote_cron_task is running"

  - name: Email Ingestion Pull Cron
    url: $AYLA_STATUS_ENDPOINT
    method: GET
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: "email_ingestion_pull_cron_task is running"

assignees:
  - roablep
  
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 */8 * * *"
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ayla-app.org
  # baseUrl: /status-monitor-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status | AylaAI
  introTitle: "**Ayla** is the world's first AI designed to help older adults manage tasks and improve memory, enhancing daily living and independence."
  introMessage: "Stay safe, sharp, and connected with Ayla."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

notifications:
  discord:
    - type: "down"
      webhookUrl: $NOTIFICATION_DISCORD_WEBHOOK_URL
    - type: "up"
      webhookUrl: $NOTIFICATION_DISCORD_WEBHOOK_URL

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
