# Change these first
owner: AylaAI # Your GitHub organization or username, where this repository lives
repo: status-monitor-upptime # The name of this repository

sites:
  - name: Ayla
    url: https://platform.ayla-app.org

assignees:
  - roablep
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 */8 * * *"
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ayla-app.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status | AylaAI
  introTitle: "**Ayla** is the world's first AI designed to help older adults manage tasks and improve memory, enhancing daily living and independence."
  introMessage: "Stay safe, sharp, and connected with Ayla."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
